name: Send Mail Job

on:
  workflow_dispatch: # Cho phép chạy bằng tay
  push:
    branches:
      - main # Đúng tên branch bạn đang dùng
  schedule:
    - cron: "0 20 * * *"

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run sendMail.js
        env:
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: node sendMail.js
